export const FINISH_LOADING = 'FINISH_LOADING'
export const START_LOADING = 'START_LOADING'

export const OPEN_POPUP = 'OPEN_POPUP'
export const CLOSE_POPUP = 'CLOSE_POPUP'

export const SHOW_TOAST = 'SHOW_TOAST'
export const HIDE_TOAST = 'HIDE_TOAST'

export const REGISTER_TOKEN = 'REGISTER_TOKEN'
export const GET_ALL_TOKEN = 'GET_ALL_TOKEN'

export const GET_VALIDATORS = 'GET_VALIDATORS'

export const SHOW_OVERLAY = 'SHOW_OVERLAY'
export const HIDE_OVERLAY = 'HIDE_OVERLAY'
export const TOGGLE_OVERLAY = 'TOGGLE_OVERLAY'

export const UPDATE_SAVED_TOKEN_SYMBOLS = 'UPDATE_SAVED_TOKEN_SYMBOLS'
export const SELECT_TOKEN = 'SELECT_TOKEN'

export const SET_USER_INFO = 'SET_USER_INFO'
export const RESET_USER_INFO = 'RESET_USER_INFO'

export const SET_ACCOUNTS = 'SET_ACCOUNTS'
export const ADD_ACCOUNTS = 'ADD_ACCOUNTS'
export const ADD_ACCOUNT = 'ADD_ACCOUNT'
export const DEL_ACCOUNT = 'DEL_ACCOUNT'
// 点击设置时，当前location
export const SETTING_INFO = 'SETTING_INFO'
// 关闭模态框
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
